version: '3'

services:
  app:
    build: .
    ports:
      - "9999:7777"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrate:
    container_name: migrate
    image: migrate/migrate:v4.15.2
    volumes:
      - ./migrations:/migrations
    entrypoint: migrate -path ./migrations -database "postgres://postgres:postgres@mypostgres:5432/postgres?sslmode=disable"
    command: up
    restart: on-failure
    depends_on:
      - mypostgres


volumes:
  postgres_data: 

