version: '3'

services:
  app:
    build: .
    ports:
      - "9999:7777"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 

