version: '3'

services:
  app:
    build: .
    ports:
      - "9999:7777"
  migrate:
    container_name: migrate
    image: migrate/migrate:v4.15.2
    volumes:
      - ./migrations:/migrations
    entrypoint: migrate -path ./migrations -database "postgres://zanjeer:zanjeer@204.12.199.7:5432/zanjeer?sslmode=disable"
    command: up
    restart: on-failure





